//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo20.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EStudyDBEntities : DbContext
    {
        public EStudyDBEntities()
            : base("name=EStudyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnquiryMaster> EnquiryMasters { get; set; }
        public virtual DbSet<FeedbackMaster> FeedbackMasters { get; set; }
        public virtual DbSet<LoginMaster> LoginMasters { get; set; }
        public virtual DbSet<NotificationMaster> NotificationMasters { get; set; }
        public virtual DbSet<StudyMaster> StudyMasters { get; set; }
        public virtual DbSet<UploadAssignmentMaster> UploadAssignmentMasters { get; set; }
        public virtual DbSet<AdminAssignmentMaster> AdminAssignmentMasters { get; set; }
        public virtual DbSet<UploadStudyMaterial> UploadStudyMaterials { get; set; }
    }
}
