//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyMaster()
        {
            this.FeedbackMasters = new HashSet<FeedbackMaster>();
            this.UploadAssignmentMasters = new HashSet<UploadAssignmentMaster>();
        }
    
        public string Name { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string EmailId { get; set; }
        public string CollegeName { get; set; }
        public string Course { get; set; }
        public Nullable<int> Yearofcourse { get; set; }
        public string MobileNo { get; set; }
        public string UserPic { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Registered_On { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackMaster> FeedbackMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadAssignmentMaster> UploadAssignmentMasters { get; set; }
    }
}
