//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadAssignmentMaster
    {
        public int Upload_Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> Upload_DT { get; set; }
        public string Uploaded_By { get; set; }
    
        public virtual StudyMaster StudyMaster { get; set; }
    }
}
